export const ADD_FAVORITE = 'ADD_FAVORITE';
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE';
export const HANDLE_MENU_FAVORITE = 'HANDLE_MENU_FAVORITE';
export const SET_LOCAL_FAVORITE = 'SET_LOCAL_FAVORITE';